### ISSUE TITLE
The Temple isn't burning yet.

### ISSUE THREAD

**Issue by GCStokum** [TempleOfPromise/TempleCAD#1]
What gives?  ;)

**Comment by GCStokum** [comment]
it's gone, we burned it ;)

**Comment by Nathanjaltman** [comment]
:)

On Tuesday, November 17, 2015, G. Carter Stokum notifications@github.com
wrote:

> it's gone, we burned it ;)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TempleOfPromise/TempleCAD/issues/1#issuecomment-157248392
> .

## 

Cheers,
Nathan

-iPhone
